-- SAPARATE LOG TABLE 
CREATE TABLE CW2.TrailLog
(
    Log_ID INT IDENTITY(1,1) PRIMARY KEY,
    Trail_ID INT NOT NULL,
    User_ID INT NOT NULL,
    Timestamp DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_TrailLog_UserID FOREIGN KEY (User_ID) REFERENCES CW2.Users(User_ID),
    CONSTRAINT FK_TrailLog_Trail_ID FOREIGN KEY (Trail_ID) REFERENCES CW2.Trail(Trail_ID)
);
